### ISSUE TITLE
Error to Initial Configuration

### ISSUE THREAD

**Issue by petryx** [hastexo/hastexo-xblock#232]
Hi,

Thanks for this awesome project.

I'm trying to deploy an environment with tutor and hastexo-xblock to learn how to use your project. But, following the Readme, appears this error

``` 
WARNING: Some services (hastexo-xblock, hastexo-xblock-reaper, hastexo-xblock-suspender) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
Starting tutor_local_mysql_1 ... done
2022/07/29 17:55:06 Ready: tcp://mysql:3306.
Loading settings lms.envs.tutor.production
Traceback (most recent call last):
  File "./manage.py", line 103, in <module>
    startup.run()
  File "/openedx/edx-platform/lms/startup.py", line 20, in run
    django.setup()
  File "/openedx/venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/openedx/venv/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/openedx/venv/lib/python3.8/site-packages/django/apps/config.py", line 224, in create
    import_module(entry)
  File "/opt/pyenv/versions/3.8.12/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'hastexo'

```  

Can you help to solve this issue?

**Comment by petryx** [comment]
Solved:
After configuring the  plugin hastexo. Is necessary run:

```
tutor images build openedx
```
